### ISSUE TITLE
LBA MLE Example

### ISSUE THREAD

**Issue by davidt0x** [yxlin/ggdmc#2]
Hi,

First, thanks for releasing this package. I had a bit of trouble reproducing the example for MLE of the LBA model presented here: https://yxlin.github.io/basics/mle/. This is using version 0.2.6 in CRAN on Windows. I tried also using the latest from GitHub but this introduced some runtime errors.

For version 0.2.6, I had to make a slight modification to the code presented to convert likelihood_norm call to simply likelihood. Not sure if this is correct but I assumed since likelihood_norm does not seem to exist in version 0.2.6.

I have included my script and output below. As you can see the parameters are not recovered correctly. Any insights into what I might be doing wrong? I am using the incorrect likelihood? 

Thanks,
Dave

```
library(ggdmc)
model <- BuildModel(
  p.map     = list(A = "1", B = "1", t0 = "1", mean_v = "M", sd_v = "1",
                   st0 = "1"),
  match.map = list(M = list(s1 = 1, s2 = 2)),
  factors   = list(S = c("s1", "s2")),
  constants = c(st0 = 0, sd_v = 1),
  responses = c("r1", "r2"),
  type      = "norm")

p.vector <- c(A = .75, B = 1.25, t0 = .15, mean_v.true = 2.5, mean_v.false = 1.5)
ntrial <- 1e3

## use the seed option to make sure I always replicate the result
## remove it, if you want to see the stochastic process.
dat <- simulate(model, nsim = ntrial, ps = p.vector, seed = 123)
dmi <- BuildDMI(dat, model)

## This is to create a column in the data frame to indicate
## correct and error responses.
dmi$C <- ifelse(dmi$S == "s1" & dmi$R == "r1", TRUE,
                ifelse(dmi$S == "s2" & dmi$R == "r2", TRUE,
                       ifelse(dmi$S == "s1" & dmi$R == "r2" ,FALSE,
                              ifelse(dmi$S == "s2" & dmi$R == "r1", FALSE, NA))))

prop.table(table(dmi$C))


objective_fun <- function(par, data) {
  den <- likelihood(par, data)
  return(-sum(log(den)))
}


p.prior <- BuildPrior(
  dists = c("tnorm", "tnorm", "beta", "tnorm", "tnorm"),
  p1    = c(A = 1, B = 1, t0 = 1, mean_v.true = 1, mean_v.false = 1),
  p2    = c(1,  1,  1, 1, 1),
  lower = c(rep(0, 3),  rep(NA, 2)),  
  upper = c(rep(NA, 2), 1, rep(NA, 2)))

init_par <- rprior(p.prior)
names(init_par) <- c("A", "B", "t0", "mean_v.true", "mean_v.false")
res <- nlminb(objective_fun, start = init_par, data = dmi, lower = 0)
round(res$par, 2)  ## remember to check res$convergence

#         A            B           t0  mean_v.true mean_v.false 
#        0.00         2.00         0.07         2.73         1.83 

```

**Comment by yxlin** [comment]
Hi David,

Thank you for being interested in ggdmc and report this bug. I apology that I cause the problem of installation for the Github version , because I was experimenting a new diffusion model routine (Blurton, S., P., Kesselmeier, M., & Gondan, M., 2017), which needs numerical integration functions from GNU gsl (Blurton et al's equation plus the need to accommodate variabilities).  Therefore, in the process, I included some gsl libraries in the package. To get Windows to work also with gsl libraries, I must manually import these gsl libraries in the package (i.e., modify the gsl source codes and add them in the C++ codes in ggdmc.) On Linux, I can rely on the system libraries. However, after I finished the Linux part of this diffusion model routine and I then went on to another more pressing project. 

I have now removed the culprit, FCalculator_new.cpp and updated the Github. Because this new routine is to speed up the computation for diffusion model when one needs to set higher precision (>4), it would not and should not affect other models in the package.

As for the error occurs in the version of 0.2.6, if you can post your script here (or send to me) particularly how you modify "likelihood_norm" function, I could test it and see where the error may come from.  The Github version now internalizes how the function decides what cognitive model (LBA, DDM or CDDM) a data-model instance carries, so "likelihood_norm" is deprecated. Simply call "likelihood" to read a data-model instance, the "likelihood" function should be able to recognize which model's likelihood function it should call. 

I have also updated the tutorial, https://yxlin.github.io/basics/mle/ , to reflect the change from using S3 (0.2.6.0 CRAN version) to using S4 class (Github version).

I hope the answer helps. 

Y.-S. Lin

**Comment by davidt0x** [comment]
Hi, 

Thanks for the quick response. 

First, I just tried to install the latest master from github on windows an everything worked. I was getting the missing GSL errors before so thanks! I had also got it installed on linux and I did encounter the S3 vs S4 object issues so thanks for fixing that in the tutorial as well.

As for my problem with the MLE example. I played around a bit more with the latest version and actually got things to converge and the parameters seemed to be recovered. However, just a note, I had to set ntrials higher than reported in the tutorial. Below are the results from my test.

```
   ntrial    A    B   t0 mean_v.true mean_v.false              convergence
1:  1e+02 1.30 0.61 0.30        2.58         1.34 relative convergence (4)
2:  1e+03 0.00 2.00 0.07        2.73         1.83 singular convergence (7)
3:  1e+04 0.63 1.50 0.10        2.60         1.62 relative convergence (4)
4:  1e+05 0.73 1.28 0.14        2.51         1.51 relative convergence (4)
5:  1e+06 0.75 1.25 0.15        2.50         1.50 relative convergence (4)
```

Does this seem reasonable to you? If so, I think you can close this issue. My code is pasted below.

```
require(dplyr)
require(ggdmc)
library(data.table)

fitModel <- function(ntrial)
{

  model <- BuildModel(
      p.map     = list(A = "1", B = "1", t0 = "1", mean_v = "M", sd_v = "1",
                       st0 = "1"),
      match.map = list(M = list(s1 = 1, s2 = 2)),
      factors   = list(S = c("s1", "s2")),
      constants = c(st0 = 0, sd_v = 1),
      responses = c("r1", "r2"),
      type      = "norm")
  
  p.vector <- c(A = .75, B = 1.25, t0 = .15, mean_v.true = 2.5, mean_v.false = 1.5)
  
  ## I used the seed option to make sure I always replicate the result.
  dat <- simulate(model, nsim = ntrial, ps = p.vector, seed = 123)
  dmi <- BuildDMI(dat, model)
  
  
  ## This is to create a column in the data frame to indicate
  ## correct and error responses.
  dmi@data$C <- ifelse(dmi@data$S == "s1" & dmi@data$R == "r1", TRUE,
                       ifelse(dmi@data$S == "s2" & dmi@data$R == "r2", TRUE,
                              ifelse(dmi@data$S == "s1" & dmi@data$R == "r2" ,FALSE,
                                     ifelse(dmi@data$S == "s2" & dmi@data$R == "r1", FALSE, NA))))
  
  prop.table(table(dmi@data$C))
  
  ## The maximum (log) likelihoods
  ## 
  den <- likelihood(p.vector, dmi)
  sum(log(den))
  
  objective_fun <- function(par, data) {
    ## Internally, C++ likelihood function will read model type, and
    ## new Likelihood constructor (in Likelihood.hpp) will read S4 slot.
    ## So here data variable is OK to be a data-model instance
    den <- likelihood(par, data)
    return(-sum(log(den)))
  }
  
  p.prior <- BuildPrior(
    dists = c("tnorm", "tnorm", "beta", "tnorm", "tnorm"),
    p1    = c(A = 1, B = 1, t0 = 1, mean_v.true = 1, mean_v.false = 1),
    p2    = c(1,  1,  1, 1, 1),
    lower = c(rep(0, 3),  rep(NA, 2)),  
    upper = c(rep(NA, 2), 1, rep(NA, 2)))
  
  init_par <- rprior(p.prior)
  names(init_par) <- c("A", "B", "t0", "mean_v.true", "mean_v.false")
  res <- nlminb(objective_fun, start = init_par, data = dmi, lower = 0)
  out <- round(res$par, 2)  ## remember to check res$convergence
  out <- data.table(t(out))
  out$convergence <- res$message
  out <- cbind(data.table(ntrial=ntrial), out)
  return(out)
}

rbindlist(lapply(c(1e2, 1e3, 1e4, 1e5, 1e6), fitModel))
```

**Comment by yxlin** [comment]
Hi David,

Really appreciated your feedback. Yes. That is expected. 1e4 would give relatively near asymptotic recovery, but not perfect, partly because A and B (so b) parameters are correlated.

Y.-S. Lin
