### ISSUE TITLE
trying to get slot "dmi" from an object (class "model") that is not an S4 object

### ISSUE THREAD

**Issue by hcp4715** [yxlin/ggdmc#4]
Hi, Yi-Shen,

Thanks for sharing your package.

I encountered an error when I tried to reproduce the code in the tutorial: https://yxlin.github.io/fixed-effect-model/one_participant/

Everything worked until the posterior predictive check:

```
> pp  <- predict_one(fit, xlim = c(0, 5))
Error in predict_one(fit, xlim = c(0, 5)) : 
  trying to get slot "dmi" from an object (class "model") that is not an S4 object 
```
The same problem occured when I tried to reproduce the code in README file

```
## Set up model ----
## fixing sv & sz to 0, makes to set up a Wiener diffusion model
require(ggdmc)
model <- BuildModel(
  p.map     = list(a = "1", v="1", z="1", d="1", sz="1", sv="1", t0="1", 
                   st0="1"),
  match.map = list(M = list(s1 = "r1", s2 = "r2")),
  factors   = list(S = c("s1", "s2")),
  responses = c("r1","r2"),
  constants = c(st0 = 0, d = 0, sv = 0, sz = 0),  
  type      = "rd")   


> npar <- model@npar
Error: trying to get slot "npar" from an object (class "model") that is not an S4 object 
```
Here is my system information:
```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_HK.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8 dplyr_1.0.0       ggdmc_0.2.6.0 
```

**Comment by yxlin** [comment]
Hi Chuan-Peng,

Thank you very much for reporting the issue. This is a version problem, which is caused by a transition from S3 to S4. I have updated the document for fitting data from [one participant](https://yxlin.github.io/fixed-effect-model/one_participant/) to accommodate such problem. In essence, the predict_one function had been changed to use S4 extractor, "@", but the version 0.2.6.0 is still on S3 class, so it extracts list elements by using dollar sign, "$". I made up a temporary wrapper function to probe whether the user is on version 0.2.6.0 or on a later version and select either the function, predict_one0260 or the function predict_one0280.  

The error you encounter on the README is similar the, perhaps, more convenient way to extract the number of model parameter, 'model@par" works for a recent version (>0.2.7.5) 

`npar <- model@npar`

To achieve the same effect, for the version of 0.2.6.0, you can do this:
`npar <- length(GetPNames(model))`

**Comment by hcp4715** [comment]
@yxlin thanks for your quick response!
